### ISSUE TITLE
Broken build: unable to execute 'gcc': No such file or directory

### ISSUE THREAD

**Issue by botanegg** [tmaier/docker-compose#19]
Currently building is broken, due to devel packages wasn`t installed
For solving that you need to install some devel packeges from alpine repos

Some info from documentation:
```
https://docs.docker.com/compose/install/
INSTALL USING PIP
For alpine, the following dependency packages are needed: py-pip, python-dev, libffi-dev, openssl-dev, gcc, libc-dev, and make.
```

**Comment by tmaier** [comment]
Related issue: https://github.com/docker/compose/issues/6617#issuecomment-477974325
