### ISSUE TITLE
doesnt work with overlay2

### ISSUE THREAD

**Issue by chuegel** [tmaier/docker-compose#2]
```
unknown flag: --storage-driver
```

```
docker run -d   --name gitlab-dind   --privileged   --restart always   --network gitlab-runner-net   -v /var/lib/docker   tmaier/docker-compose     --storage-driver=overlay2
```
```
Linux  4.13.3-041303-generic #201709200606 SMP Wed Sep 20 10:12:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tmaier** [comment]
I have no time to try it out. I think the used base image defines `CMD ["sh"]`.

So you should use 

```
docker run -d   --name gitlab-dind   --privileged   --restart always   --network gitlab-runner-net   -v /var/lib/docker   tmaier/docker-compose docker-compose  --storage-driver=overlay2
```

**Comment by chuegel** [comment]
Hi, thx for your reply. 
Unfortunately that doesnt work either.

**Comment by tmaier** [comment]
Can you please see if your command option exists at https://docs.docker.com/compose/reference/

**Comment by tmaier** [comment]
Hi @huegelc, how are you doing? Any update on this?

I assume `--storage-driver` to not be a valid attribute for docker-compose. Please consider to append it after `docker run`.

I am closing the issue for now. Please reopen, when my assumption is wrong.
