### ISSUE TITLE
Can we add buildx support?

### ISSUE THREAD

**Issue by hansbogert** [tmaier/docker-compose#32]
I'm starting to rely on docker buildx for its intermediate stages cache support, can we add buildx support to this image?

**Comment by tmaier** [comment]
What do you mean exactly? Can you provide a link? What is missing?

**Comment by hansbogert** [comment]
sorry, I've been exposed to it too much. But it's an installed-by-default option for about any docker distribution (docker desktop, docker through APT/deb, etc), except when you use their own docker image.

Please see https://docs.docker.com/buildx/working-with-buildx/

**Comment by tmaier** [comment]
Hi @hansbogert,

I am undecided. Somehow I would like the users of this image to have a say in this. But that kind of voting feature does not exist.

Can you prepare a Pull Request so that we see the impact from image size perspective and if it works for all versions supported

**Comment by petski** [comment]
As a FYI, someone is working to get `buildx` and `compose` (docker compose v2) part of the official docker images. See https://github.com/docker-library/docker/pull/361

**Comment by tmaier** [comment]
@petski this is great news!
I also tested it. It works.

This means we can deprecate this Docker image here. See 78b050b0dfadf5b328b891ac5945219f742b5d35
