### ISSUE TITLE
The latest version of docker-compose is always used

### ISSUE THREAD

**Issue by Novex** [tmaier/docker-compose#4]
Firstly thank you so much for providing this image - we've been using it for ages and it's been great!

We recently ran into a problem where the latest version of docker-compose seems to cause our test runners to hang if it receives too much input.

In trying to diagnose the issue, I rolled back this image to a few earlier versions (eg. `:17.09`) thinking that it would also roll back docker-compose to the earlier version, however it just rolled back the base docker version. This seems like quite a disparity, given I pulled `tmaier/docker-compose:17.09` last year and then when rebuilding the server pulled the exact same tag last week and got two different versions of docker-compose (one stable, one buggy).

Would you consider pinning docker-compose versions to the past images? Eg, docker:17.09 corresponds to a version released on Sept 27, 2017 and the most recent docker-compose version then was 1.16.1, so we'd explicitly tell pip to install that version. The same for each other tag (aside from latest).

I'm happy to go through and work out which versions correspond to which and put together a PR if you're open to it? Otherwise we can just start building our own images :)

**Comment by tmaier** [comment]
Thanks for the positive feedback. I am happy it helps you.

I like the idea, but I think we should only fix the minor version, not the parch release.
(I am sassuming they follow semver 2)

Can you prepare a pull request?

I would suggest to define the package version as ARG.

**Comment by Novex** [comment]
For sure - that makes sense.

Do you mean something like this? Eg. for `17.09/Dockerfile`:
```
ARG COMPOSE_VERSION=1.16

FROM docker:17.09
MAINTAINER Tobias Maier <tobias.maier@baucloud.com>

RUN apk add --no-cache py-pip
RUN pip install "docker-compose==${COMPOSE_VERSION}"
```
