### ISSUE TITLE
No GIT?!

### ISSUE THREAD

**Issue by kferrone** [tmaier/docker-compose#7]
This image is pretty useful but no GIT :/

Toss some GIT in there and you have yourself a deal.

**Comment by tmaier** [comment]
Hi,

I never had the need to use git in there.
Can you please elaborate your use case?

Thanks

Tobias

**Comment by kferrone** [comment]
I'm using gitlab-ci. Tried using your image with DinD strategy but it complained no git was installed.

**Comment by tmaier** [comment]
Weird. I never had this issue. Can you please add you gitlab-ci.yml or at least an excerpt.

**Comment by tmaier** [comment]
Due to non-activity, I am going to close the issue soon. Please provide an update so that we can proceed.
