### ISSUE TITLE
New versions missing

### ISSUE THREAD

**Issue by adiq** [tmaier/docker-compose#8]
Versions from 18.03 to 18.06 are missing.
Would you be so kind to add those, as I would like avoiding creating another docker image that does the same :-)

**Comment by tmaier** [comment]
Hi,

Thanks for notifying.
It should be fairly straight forward.
Could you please provide a Pull Request.
It is two lines. See README for details.

Cheers

Tobias

**Comment by tmaier** [comment]
I think @p4km9y started already doing this change. Maybe he/she can create a Pull Request?

**Comment by p4km9y** [comment]
https://github.com/tmaier/docker-compose/pull/9

**Comment by tmaier** [comment]
#9 has been merged. Thanks

**Comment by tmaier** [comment]
18.06 is not listed at https://docs.docker.com/release-notes/docker-ce/
